version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  backend_build_and_deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - node/install
      - checkout
      - eb/setup
      - run:
          name: Back-end Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
  frontend_build_and_deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - node/install
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - backend_build_and_deploy
      - frontend_build_and_deploy
